### ISSUE TITLE
Getting the error An error has occurred: Invalid Lambda Response: Received error response from Lambda: Handled

### ISSUE THREAD

**Issue by HarunPitchaipandi** [aws-samples/amazon-ai-building-better-bots#8]
Hi,

Has anything changed with the response format that is expected by Lex,

I am getting the error message,

An error has occurred: Invalid Lambda Response: Received error response from Lambda: Handled  

when i try from Lex. However, the cafeOrderCoffee_test.json is giving the response as 
------------------
{
  "sessionAttributes": {},
  "dialogAction": {
    "type": "ElicitSlot",
    "intentName": "cafeOrderBeverageIntent",
    "slots": {
      "BeverageType": "mocha",
      "BeverageStrength": null,
      "Creamer": null,
      "BeverageSize": null,
      "BeverageTemp": null,
      "BeverageExtras": null
    },
    "slotToElicit": "BeverageSize"
  }
}
---------------------

Thanks,

**Comment by nhira** [comment]
We've seen this if the underlying Lambda has a runtime issue.  The log entry from Lambda in response to the event from Lex is where I would look for an error.

Hope this helps.  Please reopen if needed.
